INSERT INTO `usuario` (`idUsuario`,`nombre`,`cargo`,`departamento`,`tipo`) VALUES (1,"Bruno Hartman","Auxiliar_B","Gestión_planificación_y_estrategia_de_servicios","Administrador"),(2,"Fleur Sims","SubJefe","Control_de_riesgos","Administrador"),(3,"Kasimir Stevenson","Auxiliar_A","Sistemas_e_infraestructuras","Administrador"),(4,"Galvin Harrell","Jefe","Sistemas_e_infraestructuras","Desarrollador"),(5,"Faith Conrad","Jefe","Gestión_planificación_y_estrategia_de_servicios","Administrador"),(6,"Christen Webster","Jefe","Comunicaciones","Desarrollador"),(7,"Dane Pollard","Jefe","Negocio_y_aplicaciones_empresariales","Desarrollador"),(8,"Chelsea Jimenez","Jefe","Control_de_riesgos","Desarrollador"),(9,"Aurelia Fisher","SubJefe","Sistemas_e_infraestructuras","Desarrollador"),(10,"Daryl Barton","Auxiliar_B","Centro_de_atención_al_usuario","Administrador");
INSERT INTO `usuario` (`idUsuario`,`nombre`,`cargo`,`departamento`,`tipo`) VALUES (11,"Laith Sharp","Auxiliar_B","Centro_de_atención_al_usuario","Administrador"),(12,"Gannon Kirk","Jefe","Gestión_planificación_y_estrategia_de_servicios","Administrador"),(13,"George Sawyer","SubJefe","Comunicaciones","Administrador"),(14,"Jesse Hutchinson","Jefe","Negocio_y_aplicaciones_empresariales","Desarrollador"),(15,"Bianca Mueller","Auxiliar_B","Negocio_y_aplicaciones_empresariales","Desarrollador"),(16,"Hedwig Williams","Auxiliar_B","Comunicaciones","Administrador"),(17,"Baxter Park","SubJefe","Comunicaciones","Administrador"),(18,"Martin Fowler","Auxiliar_A","Sistemas_e_infraestructuras","Desarrollador"),(19,"Kyra Shannon","Auxiliar_A","Gestión_planificación_y_estrategia_de_servicios","Desarrollador"),(20,"Shelly Wilson","Auxiliar_B","Control_de_riesgos","Administrador");
INSERT INTO `usuario` (`idUsuario`,`nombre`,`cargo`,`departamento`,`tipo`) VALUES (21,"Emery Trujillo","Auxiliar_A","Sistemas_e_infraestructuras","Desarrollador"),(22,"Sharon White","Jefe","Negocio_y_aplicaciones_empresariales","Administrador"),(23,"Juliet Estrada","Auxiliar_A","Centro_de_atención_al_usuario","Administrador"),(24,"Brandon Goodwin","Auxiliar_B","Gestión_planificación_y_estrategia_de_servicios","Administrador"),(25,"Ronan Adkins","Auxiliar_B","Desarrollo_y_nuevas_tecnologías","Desarrollador"),(26,"Candice Mccall","Jefe","Desarrollo_y_nuevas_tecnologías","Administrador"),(27,"Griffith Reeves","Auxiliar_A","Control_de_riesgos","Administrador"),(28,"Victoria Baird","Auxiliar_B","Control_de_riesgos","Administrador"),(29,"Pearl Avery","Auxiliar_A","Desarrollo_y_nuevas_tecnologías","Administrador"),(30,"Sebastian May","Auxiliar_B","Control_de_riesgos","Desarrollador");
INSERT INTO `usuario` (`idUsuario`,`nombre`,`cargo`,`departamento`,`tipo`) VALUES (31,"Keaton Dale","SubJefe","Sistemas_e_infraestructuras","Administrador"),(32,"Alexa Douglas","SubJefe","Comunicaciones","Desarrollador"),(33,"September Flynn","Jefe","Centro_de_atención_al_usuario","Desarrollador"),(34,"Naida Stephens","Jefe","Gestión_planificación_y_estrategia_de_servicios","Desarrollador"),(35,"Rhiannon Sanford","SubJefe","Sistemas_e_infraestructuras","Desarrollador"),(36,"Hedy Kelley","SubJefe","Negocio_y_aplicaciones_empresariales","Administrador"),(37,"Judith Winters","Auxiliar_A","Gestión_planificación_y_estrategia_de_servicios","Desarrollador"),(38,"Malachi Mcmahon","Auxiliar_B","Centro_de_atención_al_usuario","Desarrollador"),(39,"Sandra Bentley","Auxiliar_B","Desarrollo_y_nuevas_tecnologías","Administrador"),(40,"Sawyer Valencia","Auxiliar_A","Desarrollo_y_nuevas_tecnologías","Administrador");
INSERT INTO `usuario` (`idUsuario`,`nombre`,`cargo`,`departamento`,`tipo`) VALUES (41,"Nora Mays","Jefe","Desarrollo_y_nuevas_tecnologías","Desarrollador"),(42,"Aretha Sykes","Auxiliar_A","Comunicaciones","Desarrollador"),(43,"Mason Garrison","Auxiliar_A","Gestión_planificación_y_estrategia_de_servicios","Administrador"),(44,"Lael Saunders","Auxiliar_A","Centro_de_atención_al_usuario","Administrador"),(45,"Gemma Ramos","Auxiliar_B","Gestión_planificación_y_estrategia_de_servicios","Desarrollador"),(46,"Kiara Maddox","Jefe","Centro_de_atención_al_usuario","Desarrollador"),(47,"Brady Mathews","Auxiliar_B","Centro_de_atención_al_usuario","Desarrollador"),(48,"Keefe Blair","Auxiliar_B","Desarrollo_y_nuevas_tecnologías","Administrador"),(49,"Kermit Soto","Auxiliar_A","Desarrollo_y_nuevas_tecnologías","Desarrollador"),(50,"Reagan Head","SubJefe","Comunicaciones","Desarrollador");




INSERT INTO `proyecto` (`idProyecto`,`nombre`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`idCreador`,`estado`) VALUES (100,"Proyecto Tienda","M","2020-05-10 04:26:18","2021-01-29 12:01:56",28,"0"),(101,"Proyecto Oficina","B","2020-02-01 05:42:26","2020-12-01 05:02:55","12","1"),(102,"Proyecto Banco","B","2020-12-16 18:57:55",NULL,44,"1"),(103,"Proyecto Hospital","A","2020-01-17 08:31:31","2020-02-03 11:30:44",5,"1"),(104,"Proyecto Administracion Escolar","A","2021-09-29 16:33:09",NULL,44,"0"),(105,"Proyecto Casa","B","2021-08-10 10:18:51","2020-07-17 18:53:44",23,"0"),(106,"Proyecto Experimental","A","2021-07-04 15:22:30","2020-10-28 11:40:13",2,"1"),(107,"Proyecto Hotel","B","2021-09-20 06:18:42","2021-06-01 11:40:49",26,"0"),(108,"Proyecto Periodico","B","2020-01-14 15:05:11","2021-07-11 05:05:10",48,"1"),(109,"Proyecto Red Social","A","2020-07-17 01:07:01",NULL,44,"1");


INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1000,"Como VP de Mercadeo, quiero seleccionar el período de tiempo en el cual realizaré la revisión de las ventas.","Finalizada","A",10/05/2020,29/01/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",100,3,50);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1001,"Como VP de Mercadeo, puedo clasificar la información de ventas por región geográfica y productos.","Finalizada","M",10/08/2021,17/07/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",105,16,6);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1002,"Como un operador hotelero, quiero establecer la tarifa óptima para las habitaciones en base a los precios del año anterior.","Finalizada","B",17/07/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",109,48,45);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1003,"Como un operador hotelero, quiero establecer la tarifa óptima para las habitaciones en base a las tarifas de otros hoteles comparables con el mío.","En Preparacion","A",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,26,50);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1004,"Como Cliente, quiero suscribirme a un nuevo plan de T.V. por cable por medio del sitio web.","Finalizada","M",10/08/2021,17/07/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",105,13,32);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1005,"Como Cliente, quiero pagar mi suscripción mensual vía sitio web por medio de transferencia bancaria o tarjeta de crédito.","Finalizada","B",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,27,7);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1006," Como Cliente, quiero suscribirme a un canal de T.V Premium por períodos flexibles de tiempo por medio del sitio web.","Finalizada","A",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,40,37);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1007,"Como Cliente, consultar un listado de las suscripciones de Pay per View que se han realizado en mi cuenta.","Finalizada","M",04/07/2021,28/10/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",106,26,21);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1008,"Como Vendedor, quiero registrar los productos y cantidades que me solicita un cliente para crear un pedido de venta.","Finalizada","B",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,11,33);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1009,"Como Supervisor de ventas, quiero consultar un listado de los pedidos de venta que han sido registrados y aún no han sido procesados.","Finalizada","A",29/09/2021,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",104,11,8);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1010,"Como Gerente de ventas, quiero consultar los pedidos de venta procesados clasificándolos por vendedor, región y líneas de producto.","En Preparacion","M",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,43,19);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1011," Como Analista de logística, quiero seleccionar un pedido de venta y enviarlo al almacén para que procedan con su preparación.","Finalizada","B",04/07/2021,28/10/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",106,22,45);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1012,"Como Analista de almacén, quiero listar todos los pedidos de venta recibidos que debo preparar.","Finalizada","A",04/07/2021,28/10/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",106,48,47);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1013,"Como Analista de logística, quiero poder consultar todos los pedidos preparados listos para ser despachados.","Finalizada","M",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,23,8);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1014,"Como Analista de logística, quiero que el sistema me sugiera la ruta más corta en base a una serie de despachos de mercancía y un transporte.","Finalizada","B",29/09/2021,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",104,40,4);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1015,"Como Analista de compras, quiero crear una nueva solicitud de cotización.","En Desarrollo ","A",29/09/2021,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",104,12,35);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1016," Como Analista de compras, quiero definir si una solicitud de cotización es de adjudicación directa o de licitación.","En Preparacion","M",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,31,50);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1017,"Como Gerente de compras, quiero que el sistema requiera de mi aprobación para toda solicitud de cotización de adjudicación directa con monto mayor a USD 5.000.","Finalizada","B",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,39,38);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1018,"Como Analista de compras, quiero que el sistema notifique vía correo electrónico a los proveedores cuando se ha enviado una cotización de licitación.","Finalizada","A",17/07/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",109,16,45);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1019,"Como Representante de proveedor, quiero poder consultar los procesos de licitación que están en curso.","En Desarrollo ","M",16/12/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",102,10,8);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1020,"Como Representante de proveedor, quiero ofertar una cotización para un proceso que esté abierto por licitación.","En Preparacion","B",17/01/2020,03/02/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",103,39,45);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1021," Como Ejecutivo de cuenta, quiero consultar los datos de un cliente suministrándole al sistema su documento de identidad o código de cliente.","Finalizada","A",16/12/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",102,26,46);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1022,"Como Ejecutivo de cuenta, quiero poder abrir una nueva cuenta de cheques a un cliente, seleccionando el código de cliente y producto bancario.","En Desarrollo ","M",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,12,42);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1023,"Como Ejecutivo de cuenta, quiero registrar una nueva solicitud de crédito hipotecario a mi cliente.","Finalizada","B",10/08/2021,17/07/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",105,20,37);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1024,"Como Ejecutivo de cuenta, quiero que el sistema me indique cuales son los documentos que debo solicitar al cliente para procesar su solicitud de crédito hipotecario.","Finalizada","A",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,12,37);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1025,"Como Analista de crédito hipotecario, quiero aprobar una solicitud de crédito hipotecario para que sea evaluada por el comité de crédito.","Finalizada","M",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,36,19);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1026,"Como Presidente Ejecutivo, quiero que el sistema requiera de mi aprobación para todo crédito a otorgar cuyo monto exceda los USD 10 MM.","Finalizada","B",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,36,41);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1027,"Como cliente, quiero poder ejecutar tu producto en todas las versiones de Windows, desde Windows 95 en adelante.","Finalizada","A",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,23,14);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1028,"Como Vicepresidente de Tecnología, quiero que el sistema utilice la base de datos de pedidos existente en lugar de crear una nueva, con la finalidad de evitar el tener que mantener una nueva base de datos.","Finalizada","M",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,20,50);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1029,"Como usuario, quiero que el sitio web responda a toda transacción o funcionalidad de negocio en menos de 5 segundos.","Finalizada","B",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,29,15);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1030,"Como usuario, quiero que el sitio web esté disponible el 99,999% de las veces que intente accederlo.","Finalizada","A",17/01/2020,03/02/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",103,11,21);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1031,"Como una persona que habla un idioma basado en el latín, yo podría querer ejecutar tu software algún día.","Finalizada","M",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,26,15);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1032,"Como usuario de poder, quiero especificar archivos para realizar copias de seguridad ","Finalizada","B",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,27,32);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1033,"Como usuario, quiero indicar carpetas que no deben respaldarse","Finalizada","A",29/09/2021,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",104,23,14);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1034,"Como usuario, quiero indicar carpetas que no deben respaldarse","En Preparacion","M",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,22,49);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1035,"COMO usuario QUIERO acceder a la agenda de enfermería de forma segura PARA usar sus funcionalidades","Finalizada","B",04/07/2021,28/10/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",106,5,9);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1036,"Como Gerente de compras, quiero que el sistema requiera de mi aprobación para toda solicitud de cotización de adjudicación directa con monto mayor a USD 5.000.","Finalizada","A",04/07/2021,28/10/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",106,29,42);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1037,"Como Analista de compras, quiero que el sistema notifique vía correo electrónico a los proveedores cuando se ha enviado una cotización de licitación.","Finalizada","M",17/07/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",109,39,15);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1038,"Como Representante de proveedor, quiero poder consultar los procesos de licitación que están en curso.","En Desarrollo ","B",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,10,15);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1039,"Como Representante de proveedor, quiero ofertar una cotización para un proceso que esté abierto por licitación.","Finalizada","A",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,24,50);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1040," Como Ejecutivo de cuenta, quiero consultar los datos de un cliente suministrándole al sistema su documento de identidad o código de cliente.","Finalizada","M",29/09/2021,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",104,13,47);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1041,"Como Ejecutivo de cuenta, quiero poder abrir una nueva cuenta de cheques a un cliente, seleccionando el código de cliente y producto bancario.","En Preparacion","B",17/07/2020,NULL,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",109,17,38);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1042,"Como Ejecutivo de cuenta, quiero registrar una nueva solicitud de crédito hipotecario a mi cliente.","En Preparacion","A",10/08/2021,17/07/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",105,11,14);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1043,"Como Ejecutivo de cuenta, quiero que el sistema me indique cuales son los documentos que debo solicitar al cliente para procesar su solicitud de crédito hipotecario.","Finalizada","M",01/02/2020,01/12/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",101,10,14);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1044,"Como usuario, quiero que el sitio web responda a toda transacción o funcionalidad de negocio en menos de 5 segundos.","Finalizada","B",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,2,21);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1045,"Como usuario, quiero que el sitio web esté disponible el 99,999% de las veces que intente accederlo.","Finalizada","A",17/01/2020,03/02/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",103,31,8);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1046,"Como una persona que habla un idioma basado en el latín, yo podría querer ejecutar tu software algún día.","Finalizada","M",14/01/2020,11/07/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",108,26,37);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1047,"Como Ejecutivo de cuenta, quiero registrar una nueva solicitud de crédito hipotecario a mi cliente.","Finalizada","B",17/01/2020,03/02/2020,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",103,20,37);
INSERT INTO `historia` (`idHistoria`,`nombre`,`estado`,`prioridad`,`fecha_creacion`,`fecha_finalizacion`,`descripcion`,`idProyecto`,`idAdministrador`,`idDesarrollador`) VALUES (1048,"Como Ejecutivo de cuenta, quiero que el sistema me indique cuales son los documentos que debo solicitar al cliente para procesar su solicitud de crédito hipotecario.","Finalizada","B",20/09/2021,01/06/2021,"Lorem ipsum dolor sit amet consectetur, adipiscing elit integer eu quam, tempus feugiat felis rhoncus.",107,3,30);
